### ISSUE TITLE
카카오 로그인 수정사항!!!

### ISSUE THREAD

**Issue by bini59** [Team-Connecter/Digital-Guiljabi-Back#115]
1. 카카오 로그인 링크 받는거 수정사항!!
https://kauth.kakao.com/oauth/authorize?client_id=78f9db867e8831b570efd5e479f72a08&redirect_uri=http%3A%2F%2F118.67.133.198%3A8080%2Fapi%2Flogin%2Fcallback&response_type=code

카카오 로그인 링크를 요청을 하면 다음과 같은 형태로 오는데욤 ( GET /api/login/kakao )
여기서 redirect_uri = ~~이거는 빼고

```
https://kauth.kakao.com/oauth/authorize?client_id=78f9db867e8831b570efd5e479f72a08
```
딱 위에 이거부분만 보내주시면 좋을 것 같아욤.

2. code 이용해서 로그인 후, jwt 토큰 받아오는 API 구현 필요

지금 현재는 로그인을 하게 되면

![image](https://github.com/Team-Connecter/Digital-Guiljabi-Back/assets/51144791/814352c6-f29a-4cf8-861e-d2d496ef1dd5)

위와 같이 이동이 되는데

이걸 프론트에서 받아서, 
code를 backend쪽으로 보내주면, backend에서 code를 이용해 카카오 로그인 처리를 한 후, 
jwt 토큰만 응답으로 보내주는 API가 있어야 할 것 같아욤.

**Comment by bini59** [comment]
![image](https://github.com/Team-Connecter/Digital-Guiljabi-Back/assets/51144791/5bce586a-a052-48ee-a8aa-e52f662be20a)

수정된 API 테스트 했을때 500번 에러가 계속 발생중입니다.. 확인 부탁드려요!

**Comment by Juhyorim** [comment]
수정완료!
