### ISSUE TITLE
댓글을 비 로그인 상태에서 불러올 수 없는 이슈

### ISSUE THREAD

**Issue by bini59** [Team-Connecter/Digital-Guiljabi-Back#63]
![image](https://github.com/Team-Connecter/Digital-Guiljabi-Back/assets/51144791/8eb76455-acc3-4df9-bdad-2c00f86e3329)

위 사진은 로그인을 했을 경우의 사진입니다.

![image](https://github.com/Team-Connecter/Digital-Guiljabi-Back/assets/51144791/97650512-5e8c-4271-8858-edbe6f3ca268)

위 사진은 로그아웃 상태의 사진입니다.

로그인이 되어있지 않으면 댓글을 불러올 수 없다고 생각됩니다. 확인 부탁드립니다.

**Comment by Juhyorim** [comment]
수정완료!
