### ISSUE TITLE
좋아요 취소

### ISSUE THREAD

**Issue by Commeci** [Team-Connecter/Digital-Guiljabi-Back#66]
![스크린샷 2023-08-09 180933](https://github.com/Team-Connecter/Digital-Guiljabi-Back/assets/97789190/23d2190d-7be7-4bbf-87d1-a9870348735c)
좋아요를 누르면 좋아요가 올라가는데, 취소를 누르면 내려가지 않음.

**Comment by Juhyorim** [comment]
영은이가 완료!
